version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
    groups:
      wows-toolkit:
        patterns:
          - wowsunpack
          - wows-data-mgr
    ignore:
      - dependency-name: pickled
      - dependency-name: reqwest
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
